using System;
using System.Collections.Generic;
using System.Linq;

namespace DiscordGuardianBot
{
    /// <summary>
    /// This class will be used for selecting Angela Lansbury gifs without poluting the main code
    /// </summary>
    class Angela
    {
        /// <summary>
        /// Used for randomly picking a pun from a list to return as a string
        /// </summary>
        public static string RandomPun()
        {
            // Generate the list
            List<string> puns = new List<string>
            {
                "What do you call a fake noodle? An Impasta.",
                "I would avoid the sushi if I was you. It’s a little fishy.",
                "Want to hear a joke about paper? Nevermind it’s tearable.",
                "Why did the cookie cry? Because his father was a wafer so long!",
                "I used to work in a shoe recycling shop. It was sole destroying.",
                "What do you call a belt with a watch on it? A waist of time.",
                "How do you organize an outer space party? You planet.",
                "I went to a seafood disco last week... and pulled a mussel.",
                "Do you know where you can get chicken broth in bulk? The stock market.",
                "I cut my finger chopping cheese, but I think that I may have greater problems.",
                "My cat was just sick on the carpet, I don’t think it’s feline well.",
                "Why did the octopus beat the shark in a fight? Because it was well armed.",
                "How much does a hipster weigh? An instagram.",
                "What did daddy spider say to baby spider? You spend too much time on the web.",
                "Atheism is a non-prophet organisation.",
                "There’s a new type of broom out, it’s sweeping the nation.",
                "What cheese can never be yours? Nacho cheese.",
                "What did the Buffalo say to his little boy when he dropped him off at school? Bison.",
                "Have you ever heard of a music group called Cellophane? They mostly wrap.",
                "Why does Superman gets invited to dinners? Because he is a Supperhero.",
                "How was Rome split in two? With a pair of Ceasars.",
                "The shovel was a ground breaking invention.",
                "A scarecrow says, 'This job isn't for everyone, but hay, it's in my jeans.'",
                "A Buddhist walks up to a hot dog stand and says, 'Make me one with everything.'",
                "Did you hear about the guy who lost the left side of his body? He's alright now.",
                "What do you call a girl with one leg that's shorter than the other? Ilene.",
                "I did a theatrical performance on puns. It was a play on words.",
                "What do you do with a dead chemist? You barium.",
                "I bet the person who created the door knocker won a Nobel prize.",
                "Towels can’t tell jokes. They have a dry sense of humor.",
                "Two birds are sitting on a perch and one says 'Do you smell fish?'",
                "Do you know sign language? You should learn it, it’s pretty handy.",
                "What do you call a beautiful pumpkin? GOURDgeous.",
                "Why did one banana spy on the other? Because she was appealing.",
                "What do you call a cow with no legs? Ground beef.",
                "What do you call a cow with two legs? Lean beef.",
                "What do you call a cow with all of its legs? High steaks.",
                "A cross eyed teacher couldn’t control his pupils.",
                "After the accident, the juggler didn’t have the balls to do it.",
                "I used to be afraid of hurdles, but I got over it.",
                "To write with a broken pencil is pointless.",
                "I read a book on anti-gravity. I couldn’t put it down.",
                "I couldn’t remember how to throw a boomerang but it came back to me.",
                "What should you do if you are cold? Stand in the corner. It’s 90 degrees.",
                "How does Moses make coffee? Hebrews it.",
                "The energizer bunny went to jail. He was charged with battery.",
                "What did the alien say to the pitcher of water? Take me to your liter.",
                "What happens when you eat too many spaghettiOs? You have a vowel movement.",
                "The soldier who survived mustard gas and pepper spray was a seasoned veteran.",
                "Sausage puns are the wurst.",
                "What do you call a bear with no teeth? A gummy bear.",
                "Why shouldn’t you trust atoms? They make up everything.",
                "What’s it called when you have too many aliens? Extraterrestrials.",
                "Want to hear a pizza joke? Nevermind, it’s too cheesy.",
                "What do cows tell each other at bedtime? Dairy tales.",
                "Why can’t you take inventory in Afghanistan? Because of the tally ban.",
                "Why didn’t the lion win the race? Because he was racing a cheetah.",
                "What happens to nitrogen when the sun comes up? It becomes daytrogen.",
                "What’s it called when you put a cow in an elevator? Raising the steaks.",
                "What’s america’s favorite soda? Mini soda.",
                "Why did the tomato turn red? Because it saw the salad dressing.",
                "What kind of car does a sheep drive? Their SuBAHHru.",
                "What do you call a french pig? Porque.",
                "What do you call a line of rabbits marching backwards? A receding hairline.",
                "Why don’t vampires go to barbecues? They don’t like steak.",
                "How do trees access the internet? They log on.",
                "Why should you never trust a train? They have loco motives.",
                "Is your refrigerator running? Better go catch it.",
                "The future,the present and the past walked into a bar.Things got a little tense.",
                "I saw an ad for burial plots, and thought to myself this is the last thing I need.",
                "I just found out I'm colorblind. The diagnosis came completely out of the purple.",
                "I'd tell you a chemistry joke but I know I wouldn't get a reaction.",
                "Have you ever tried to eat a clock? It's very time consuming.",
                "I wondered why the baseball was getting bigger. Then it hit me.",
                "Read enough of our funny puns, and you'll be punstoppable.",
                "Yesterday a clown held the door for me. It was a nice jester.",
                "I used to go fishing with Skrillex but he kept dropping the bass.",
                "The wedding was so emotional even the cake was in tiers.",
                "What does a house wear? A dress.",
                "Why can't bicycles stand up on their own? Since they are 2 tired.",
                "I owe a lot to the sidewalks. They’ve been keeping me off the streets for years.",
                "Imagine if alarm clocks hit you back in the morning.It would be truly alarming.",
                "Why is a skeleton a bad liar? You can see right through it.",
                "What do you receive when you ask a lemon for help? Lemonaid.",
                "A man sued an airline company after it lost his luggage. Sadly, he lost his case.",
                "What does a dog say when he sits down on a piece of sandpaper? Ruff!",
                "What do you call crystal clear urine? 1080pee.",
                "At my boxing club there is only one punch bag. I hate waiting for the punch line!",
                "An untalented gymast walks into a bar.",
                "Einstein developed a theory about space, and it was about time too.",
                "I was accused of being a plagiarist, their word not mine.",
                "My friends say they don’t like skeleton puns. I should put more backbone into them.",
                "Let me FILL you in on my trip to the dentist.",
                "Why does the singer of Cheap Thrills not want us to Sia?",
                "Traveling on a flying carpet is a rugged experience.",
                "Cartoonist found dead in home. Details are sketchy.",
                "The old woman who lived in a shoe wasn’t the sole owner,there were strings attached.",
                "Did you hear about the crime in the parking garage? It was wrong on so many levels.",
                "My new diet consists of aircraft, its a bit plane.",
                "Have you ever tried to milk a cow which has been cut in half? Udder madness.",
                "Why are there fences on graveyards? Because people are dying to get in.",
                "Why do trees have so many friends? They branch out.",
                "Models of dragons are not to scale.",
                "Never discuss infinity with a mathematician, they can go on about it forever.",
                "Why don’t some couples go to the gym? Because some relationships don’t work out.",
                "Don’t trust people that do acupuncture, they’re back stabbers.",
                "A persistent banker wouldn’t stop hitting on me so I asked him to leave me a loan.",
                "I ordered a book of puns last week, but i didn't get it.",
                "People say i look better without glasses but i just can't see it.",
                "Don’t judge a meal by the look of the first course. It’s very souperficial.",
                "I heard Donald Trump is going to ban shredded cheese, and make America grate again.",
                "I relish the fact that you’ve mustard the strength to ketchup to me.",
                "What do you call a young musician? A minor.",
                "Police were called to a daycare yesterday, where a 2-year-old was resisting a rest.",
                "If artists wear sketchers do linguists wear converse?",
                "I changed my iPod name to Titanic. It’s syncing now.",
                "Jill broke her finger today, but on the other hand she was completely fine.",
                "I smeared some ketchup all over my eyes once. It was a bad idea in Heinz- sight.",
                "I flipped a coin over an issue the other day, it was quite the toss-up.",
                "I got hit in the head with a can of soda? Luckily it was a soft drink.",
                "I heard that the post office was a male dominated industry.",
                "Why isn’t suntanning an Olympic sport? Because the best you can ever get is bronze.",
                "What do you mean June is over? Julying.",
                "Why is Kylo Ren so angry? Beause he’s always Ben Solo.",
                "These reversing cameras are great. Since I got one I haven’t looked back.",
                "The candle quit his job because he felt burned out.",
                "Our maintenance guy lost his legs on the job, now he’s just a handyman.",
                "Going to bed with music on gave him sound sleep.",
                "A magic tractor drove down the road and turned into a field!",
                "I met some aliens from outer space. They were pretty down to earth.",
                "The plane flight brought my acrophobia to new heights.",
                "My phone has to wear glasses ever since it lost its contacts.",
                "I, for one, like Roman numerals.",
                "How do mountains see? They peak.",
                "The show was called Spongebob Squarepants but everyone knows the star was Patrick.",
                "This is not alcohol, water you thinking?!",
                "Novice pirates make terrible singers because they can’t hit the high seas.",
                "I told my friend she drew her eyebrows too high. She seemed surprised.",
                "The earth's rotation really makes my day.",
                "If I buy a bigger bed will I have more or less bedroom?",
                "Two peanuts were walking in a tough neighborhood and one of them was a-salted.",
                "Two ropes were walking in a tough neighborhood and one of them was a-frayed.",
                "What kind of shoes do ninjas wear? Sneakers.",
                "I got a master’s degree in being ignored; no one seems to care.",
                "After eating the ship, the sea monster said, I can’t believe I ate the hull thing.",
                "Smaller babies may be delivered by stork but the heavier ones need a crane.",
                "A bartender broke up with her boyfriend, but he kept asking her for another shot.",
                "I had a pun about insanity but then I lost it.",
                "He couldn’t work out how to fix the washing machine so he threw in the towel.",
                "Why does the man want to buy nine rackets? Cause tennis too many.",
                "Why don’t cannibals eat clowns? Because they taste funny.",
                "If I got paid in lots of Pennes I would make loads of pasta.",
                "I thought I saw a spider on my laptop, but my friend said it was just a bug.",
                "A doctor broke his leg while auditioning for a play.Luckily he still made the cast.",
                "The tale of the haunted refrigerator was chilling.",
                "Why are frogs so happy? They eat whatever bugs them.",
                "If you wear cowboy clothes are you ranch dressing?",
                "I was addicted to the hokey pokey but I turned myself around.",
                "Simba, you're falling behind. I must ask you to Mufasa.",
                "I bought a wooden whistle but it wooden whistle.",
                "The bomb didn't want to go off. So it refused.",
                "The sore mummy needed a Cairo-practor",
                "I feel sorry for shopping carts. They’re always getting pushed around.",
                "The display of still-life art was not at all moving!",
                "On Halloween October is nearly Octover.",
                "Pig puns are so boaring.",
                "Why couldn’t the dead car drive into the cluttered garage? Lack of vroom.",
                "What do you call Samsung's security guards? Guardians of the Galaxy.",
                "What does Superman have in his drink? Just ice.",
                "How does a penguin build it’s house? Igloos it together.",
                "Time flies like an arrow. Fruit flies like a banana.",
                "The safe was invented by a cop and a robber. It was quite a combination.",
                "What do you do when balloons are hurt? You helium.",
                "One hat says to the other, 'You stay here, I’ll go on a head.'",
                "How many tickles does it take to make an octopus laugh? Ten tickles.",
                "When does a farmer dance? When he drops the beet.",
                "When the scientist wanted to clone a deer, he bought a doe it yourself kit.",
                "If people ask how many puns I made in Germany I reply, 'nein'",
                "Did you hear about the invention of the white board? It was remarkable.",
                "If Donald Trump becomes president, America is going toupee.",
                "Can February March? No, but April May.",
                "I hate Russian Dolls, they are so full of themselves.",
                "What do you do to an open wardrobe? You closet.",
                "The magazine about ceiling fans went out of business due to low circulation.",
                "So what if I don’t know what apocalypse means? It’s not the end of the world!",
                "Some aquatic mammals at the zoo escaped. It was otter chaos.",
                "A backwards poem writes inverse.",
                "Getting the ability to fly would be so uplifting.",
                "I asked my friend, Nick, if he had 5 cents I could borrow. But he was Nicholas.",
                "The soundtrack for Blackfish was orcastrated.",
                "Where do you imprison a skeleton? In a rib cage.",
                "There’s a fine line between the numerator and the denominator.",
                "I used to work at a hairdresser but i just wasn’t cut out for it.",
                "Why is metal and a microwave a match made in heaven? When they met, sparks flew.",
                "The lumberjack loved his new computer. He especially enjoyed logging in.",
                "Garbage collectors are rubbish drivers!",
                "When the church relocated it had an organ transplant.",
                "Lettuce take a moment to appreciate this salad pun.",
                "The scarecrow get promoted because he was outstanding in his field.",
                "Sleeping comes so naturally to me, I could do it with my eyes closed.",
                "I never understood odorless chemicals, they never make scents.",
                "What do prisoners use to call each other? Cell phones.",
                "Why was dumbo sad? He felt irrelephant.",
                "When a clock is hungry, it goes back four seconds.",
                "Old skiers never die. They just go down hill.",
                "Did you hear about the pun that was actually funny? Neither have we.",
                "You know why I like egg puns? They crack me up!",
                "Want to hear a pun about ghosts? That's the spirit!",
                "I used to make clown shoes… which was no small feat.",
                "Did you hear about the human cannonball? Too bad he got fired!",
                "What happened when the magician got mad? She pulled her hare out!",
                "Did you hear about the circus that caught on fire? It was in tents.",
                "The one day of the week that eggs are definitely afraid of is Fry-day.",
                "A hen will always leave her house through the proper eggs-it.",
                "The man who ate too many eggs was considered to be an egg-oholic.",
                "All the hens consider the chef to be very mean because he beats the eggs.",
                "Eskimos keep all of their chilled eggs inside of the egg-loo.",
                "Under the doctor’s advice, the hen is laying off eggs for a few weeks.",
                "I had a real problem making a hard-boiled egg this morning until I cracked it.",
                "The best time of day to eat eggs is at the crack of dawn.",
                "The chicken coop only had 2 doors since if it had 4 doors it would be a sedan.",
                "Crossing a cement mixer and a chicken will result in you getting a brick layer.",
                "That reckless little egg always seems to egg-celerate when he sees the light turn yellow.",
                "Hopefully this egg pun doesn't make your brain too fried or scrambled.",
                "Don't ever have multiple people wash dishes together. It's hard for them to stay in sink.",
                "People using umbrellas always seem to be under the weather.",
                "I dissected an iris today. It was an eye-opening experience.",
                "What was Forrest Gump’s email password? 1forrest1.",
                "What planet is like a circus? Saturn, it has three rings!",
                "Before my father died he worked in a circus as a stilt walker. I used to look up to him.",
                "Why did the lion eat the tightrope walker? He wanted a well-balanced meal!",
                "I really look up to my tall friends.",
                "I hate negative numbers and will stop at nothing to avoid them.",
                "Long fairy tales have a tendency to dragon.",
                "It takes guts to make a sausage."
            };
            return puns.PickRandom();
        }
        /// <summary>
        /// Used for randomly picking a gif from a list to return as a string
        /// </summary>
        public static string RandomAngela()
        {
            // Generate the list
            List<string> gifs = new List<string>
            {
                "https://i.imgur.com/Zw9N0Zj.gifv",
                "https://i.imgur.com/HNHI7R8.gifv",
                "https://i.imgur.com/g4AsNST.gifv",
                "https://i.imgur.com/IUPakM0.gifv",
                "https://i.imgur.com/L8og9FQ.gifv",
                "https://i.imgur.com/XrWZHfw.gifv",
                "https://i.imgur.com/1YP3k5H.gifv",
                "https://i.imgur.com/pguPnex.gifv",
                "https://i.imgur.com/llM9VLc.gifv",
                "https://i.imgur.com/LxUkPqc.gifv",
                "https://i.imgur.com/lcvipK6.gifv",
                "https://i.imgur.com/1pT1his.gifv",
                "https://i.imgur.com/qXOyevq.gifv",
                "https://i.imgur.com/QRLm4Km.gifv",
                "https://i.imgur.com/e7cxdOR.gifv",
                "https://i.imgur.com/darsAux.gifv",
                "https://i.imgur.com/YmslKNT.gifv",
                "https://i.imgur.com/R74Wt1u.gifv",
                "https://i.imgur.com/iOsRfOp.gifv",
                "https://i.imgur.com/QQRrH4m.gifv",
                "https://i.imgur.com/pXV6JTO.gifv",
                "https://i.imgur.com/denNrt8.gifv",
                "https://i.imgur.com/Du2vvXx.gifv",
                "https://i.imgur.com/fplkz4p.gifv",
                "https://i.imgur.com/J2qBqS8.gifv",
                "https://i.imgur.com/utmXEEv.gifv",
                "https://i.imgur.com/jrjz2so.gifv",
                "https://i.imgur.com/qfRJLsa.gifv",
                "https://i.imgur.com/yRNSnc1.gifv",
                "https://i.imgur.com/uUniBJT.gifv",
                "https://i.imgur.com/Ar16njQ.gifv",
                "https://i.imgur.com/3mRgTWF.gifv",
                "https://i.imgur.com/wY4e3lR.gifv",
                "https://i.imgur.com/NSlAHPI.gifv",
                "https://i.imgur.com/7HJmcqk.gifv",
                "https://i.imgur.com/C7kbcFi.gifv",
                "https://i.imgur.com/gjLKPf0.gifv",
                "https://i.imgur.com/MJTl89b.gifv",
                "https://i.imgur.com/8zL6xB7.gifv",
                "https://i.imgur.com/uHKM4B1.gifv",
                "https://i.imgur.com/extkAtE.gifv",
                "https://i.imgur.com/4zEYGaZ.gifv",
                "https://i.imgur.com/SB9dq5K.gifv",
                "https://i.imgur.com/jPXH0lo.gifv",
                "https://i.imgur.com/3NnbuLF.gifv",
                "https://i.imgur.com/0kyY2rC.gifv",
                "https://i.imgur.com/f2grYDw.gifv",
                "https://i.imgur.com/h9UXEwT.gifv",
                "https://i.imgur.com/3bXnyqD.gifv",
                "https://i.imgur.com/vsJxAaC.gifv",
                "https://i.imgur.com/5FdBEdC.gifv",
                "https://i.imgur.com/8rOZJTn.gifv",
                "https://i.imgur.com/KjiIRzO.gifv",
                "https://i.imgur.com/1kBXbDA.gifv",
                "https://i.imgur.com/hdrCu7Y.gifv",
                "https://i.imgur.com/X29zFH1.gifv",
                "https://i.imgur.com/6mUbqVD.gifv",
                "https://i.imgur.com/i6nj5CK.gifv",
                "https://i.imgur.com/vbKaNrh.gifv",
                "https://i.imgur.com/5n7wgLd.gifv",
                "https://i.imgur.com/ujBvf9G.gifv",
                "https://i.imgur.com/c9Z8Hma.gifv",
                "https://i.imgur.com/jv8tJ5w.gifv",
                "https://i.imgur.com/ZUbHeKk.gifv",
                "https://i.imgur.com/pbhTxlT.gifv",
                "https://i.imgur.com/eW5zoJi.gifv",
                "https://i.imgur.com/cvfUsPh.gifv",
                "https://i.imgur.com/w741AGX.gifv",
                "https://i.imgur.com/M6GcP3V.gifv",
                "https://i.imgur.com/zLpRBFe.gifv",
                "https://i.imgur.com/sRIX7KW.gifv",
                "https://i.imgur.com/M3L1E7R.gifv",
                "https://i.imgur.com/cguzUir.gifv",
                "https://i.imgur.com/Xgats5l.gifv",
                "https://i.imgur.com/mFqUtIC.gifv",
                "https://i.imgur.com/qBlKVbM.gifv",
                "https://i.imgur.com/XIdqdzw.gifv",
                "https://i.imgur.com/A1Zk1Qz.gifv",
                "https://i.imgur.com/OJxF6Br.gifv",
                "https://i.imgur.com/ysHRiAJ.gifv",
                "https://i.imgur.com/IHDSVVf.gifv",
                "https://i.imgur.com/IqpsIUE.gifv",
                "https://i.imgur.com/1t9hkWe.gifv",
                "https://i.imgur.com/ewQkj9N.gifv",
                "https://i.imgur.com/CCXIa7S.gifv",
                "https://i.imgur.com/0z0olKt.gifv",
                "https://i.imgur.com/KpD5NPv.gifv",
                "https://i.imgur.com/jP5aSFH.gifv",
                "https://i.imgur.com/KIPyEGY.gifv",
                "https://i.imgur.com/TbpTkbH.gifv",
                "https://i.imgur.com/npuSUGu.gifv",
                "https://i.imgur.com/BlJ2TL0.gifv",
                "https://i.imgur.com/bMv9733.gifv",
                "https://i.imgur.com/nzzrEKe.gifv",
                "https://i.imgur.com/wPGILDt.gifv",
                "https://i.imgur.com/nUNPvSg.gifv",
                "https://i.imgur.com/u8sLnIl.gifv",
                "https://i.imgur.com/l7JSY23.gifv",
                "https://i.imgur.com/0aNAe7x.gifv",
                "https://i.imgur.com/B5H4dV5.gifv",
                "https://i.imgur.com/c5cKeZI.gifv",
                "https://i.imgur.com/DehEzbj.gifv",
                "https://i.imgur.com/53ICRY5.gifv",
                "https://i.imgur.com/F42h0ZG.gifv",
                "https://i.imgur.com/Z7X0jMp.gifv",
                "https://i.imgur.com/k54GQEP.gifv",
                "https://i.imgur.com/xvviuJm.gifv",
                "https://i.imgur.com/E34nY0p.gifv",
                "https://i.imgur.com/VQLdJ0W.gifv",
                "https://i.imgur.com/I88yU66.gifv",
                "https://i.imgur.com/TDFbtqD.gifv",
                "https://i.imgur.com/pp72CVf.gifv",
                "https://i.imgur.com/MfJxukv.gifv",
                "https://i.imgur.com/1JypEB2.gifv",
                "https://i.imgur.com/kLHAXVP.gifv",
                "https://i.imgur.com/xOHDRJu.gifv",
                "https://i.imgur.com/kSZO1Bw.gifv",
                "https://i.imgur.com/sfRXNPF.gifv",
                "https://i.imgur.com/fyuLKDz.gifv",
                "https://i.imgur.com/rN0wyEi.gifv",
                "https://i.imgur.com/MpGcmjU.gifv",
                "https://i.imgur.com/vWgObLD.gifv",
                "https://i.imgur.com/XAel22r.gifv",
                "https://i.imgur.com/zMVOsCG.gifv",
                "https://i.imgur.com/M8hxzWF.gifv",
                "https://i.imgur.com/DBVKu3N.gifv",
                "https://i.imgur.com/i4SH4Cd.gifv",
                "https://i.imgur.com/uBGtaF0.gifv",
                "https://i.imgur.com/rKwcRQl.gifv",
                "https://i.imgur.com/Y87M7aP.gifv",
                "https://i.imgur.com/SmMlmwm.gifv",
                "https://i.imgur.com/nvtlUpc.gifv",
                "https://i.imgur.com/U8ZnQ9K.gifv",
                "https://i.imgur.com/UH1MPDz.gifv",
                "https://i.imgur.com/i7pRJky.gifv",
                "https://i.imgur.com/R6cAVqR.gifv",
                "https://i.imgur.com/kFeKqgY.gifv",
                "https://i.imgur.com/KmtFX7O.gifv",
                "https://i.imgur.com/XXHIYPr.gifv",
                "https://i.imgur.com/ByYvvdD.gifv",
                "https://i.imgur.com/en710EQ.gifv",
                "https://i.imgur.com/BwjdO2q.gifv",
                "https://i.imgur.com/wo5Xfud.gifv",
                "https://i.imgur.com/UWm5V2q.gifv",
                "https://i.imgur.com/99mA3ek.gifv",
                "https://i.imgur.com/IGgQvjM.gifv",
                "https://i.imgur.com/XVcb04i.gifv",
                "https://i.imgur.com/yWxOIAT.gifv",
                "https://i.imgur.com/32BylPq.gifv",
                "https://i.imgur.com/Ll0W2LS.gifv",
                "https://i.imgur.com/GWFXxGy.gifv",
                "https://i.imgur.com/9UcNqzT.gifv",
                "https://i.imgur.com/G2eogqR.gifv",
                "https://i.imgur.com/yl78jZa.gifv",
                "https://i.imgur.com/LOKAEFk.gifv",
                "https://i.imgur.com/3tVUJkm.gifv",
                "https://i.imgur.com/Gyn3f3T.gifv",
                "https://i.imgur.com/Xw7qLsE.gifv",
                "https://i.imgur.com/oBhqalB.gifv",
                "https://i.imgur.com/XjK4lrM.gifv",
                "https://i.imgur.com/JytfhwO.gifv",
                "https://i.imgur.com/x6eK1vk.gifv",
                "https://i.imgur.com/Ojjn2Nh.gifv",
                "https://i.imgur.com/6bsAdft.gifv",
                "https://i.imgur.com/HSJlvSB.gifv",
                "https://i.imgur.com/R2WEiWM.gifv",
                "https://i.imgur.com/ugDT4pL.gifv",
                "https://i.imgur.com/AbNNLUW.gifv",
                "https://i.imgur.com/a0H3fKd.gifv",
                "https://i.imgur.com/B8rYdBV.gifv",
                "https://i.imgur.com/8LCX2UD.gifv",
                "https://i.imgur.com/xExWnYS.gifv",
                "https://i.imgur.com/zmK7l3a.gifv",
                "https://i.imgur.com/CDGwxyJ.gifv",
                "https://i.imgur.com/jvv3Gwd.gifv",
                "https://i.imgur.com/ARrRLPW.gifv",
                "https://i.imgur.com/UH1MPDz.gifv"
            };
            // Return a random gif
            return gifs.PickRandom();

        }
        /// <summary>
        /// Used for randomly picking a gif from a list to return as a string
        /// </summary>
        public static string RandomExcuse()
        {
            // Generate the list
            List<string> Messages = new List<string>
            {
                "clock speed",
                "solar flares",
                "electromagnetic radiation from satellite debris",
                "static from nylon underwear",
                "static from plastic slide rules",
                "global warming",
                "poor power conditioning",
                "static buildup",
                "doppler effect",
                "hardware stress fractures",
                "magnetic interference from money/credit cards",
                "dry joints on cable plug",
                "we're waiting for [the phone company] to fix that line",
                "sounds like a Windows problem, try calling Microsoft support",
                "temporary routing anomaly",
                "somebody was calculating pi on the server",
                "fat electrons in the lines",
                "excess surge protection",
                "floating point processor overflow",
                "divide-by-zero error",
                "POSIX compliance problem",
                "monitor resolution too high",
                "improperly oriented keyboard",
                "network packets travelling uphill (use a carrier pigeon)",
                "Decreasing electron flux",
                "first Saturday after first full moon in Winter",
                "radiosity depletion",
                "CPU radiator broken",
                "It works the way the Wang did, what's the problem",
                "positron router malfunction",
                "cellular telephone interference",
                "techtonic stress",
                "piezo-electric interference",
                "(l)user error",
                "working as designed",
                "dynamic software linking table corrupted",
                "heavy gravity fluctuation, move computer to floor rapidly",
                "secretary plugged hairdryer into UPS",
                "terrorist activities",
                "not enough memory, go get system upgrade",
                "interrupt configuration error",
                "spaghetti cable cause packet failure",
                "boss forgot system password",
                "bank holiday - system operating credits  not recharged",
                "virus attack, luser responsible",
                "waste water tank overflowed onto computer",
                "Complete Transient Lockout",
                "bad ether in the cables",
                "Bogon emissions",
                "Change in Earth's rotational speed",
                "Cosmic ray particles crashed through the hard disk platter",
                "Smell from unhygienic janitorial staff wrecked the tape heads",
                "Little hamster in running wheel had coronary; waiting for replacement to be Fedexed from Wyoming",
                "Evil dogs hypnotised the night shift",
                "Plumber mistook routing panel for decorative wall fixture",
                "Electricians made popcorn in the power supply",
                "Groundskeepers stole the root password",
                "high pressure system failure",
                "failed trials, system needs redesigned",
                "system has been recalled",
                "not approved by the FCC",
                "need to wrap system in aluminum foil to fix problem",
                "not properly grounded, please bury computer",
                "CPU needs recalibration",
                "system needs to be rebooted",
                "bit bucket overflow",
                "descramble code needed from software company",
                "only available on a need to know basis",
                "knot in cables caused data stream to become twisted and kinked",
                "nesting roaches shorted out the ether cable",
                "The file system is full of it",
                "Satan did it",
                "Daemons did it",
                "You're out of memory",
                "There isn't any problem",
                "Unoptimized hard drive",
                "Typo in the code",
                "Yes, yes, its called a design limitation",
                "Look, buddy:  Windows 3.1 IS A General Protection Fault.",
                "That's a great computer you have there; have you considered how it would work as a BSD machine?",
                "Please excuse me, I have to circuit an AC line through my head to get this database working.",
                "Yeah, yo mama dresses you funny and you need a mouse to delete files.",
                "Support staff hung over, send aspirin and come back LATER.",
                "Someone is standing on the ethernet cable, causing a kink in the cable",
                "Windows 95 undocumented 'feature'",
                "Runt packets",
                "Password is too complex to decrypt",
                "Boss' kid fucked up the machine",
                "Electromagnetic energy loss",
                "Budget cuts",
                "Mouse chewed through power cable",
                "Stale file handle (next time use Tupperware(tm)!)",
                "Feature not yet implemented",
                "Internet outage",
                "Pentium FDIV bug",
                "Vendor no longer supports the product",
                "Small animal kamikaze attack on power supplies",
                "The vendor put the bug there.",
                "SIMM crosstalk.",
                "IRQ dropout",
                "Collapsed Backbone",
                "Power company testing new voltage spike (creation) equipment",
                "operators on strike due to broken coffee machine",
                "backup tape overwritten with copy of system manager's favourite CD",
                "UPS interrupted the server's power",
                "The electrician didn't know what the yellow cable was so he yanked the ethernet out.",
                "The keyboard isn't plugged in",
                "The air conditioning water supply pipe ruptured over the machine room",
                "The electricity substation in the car park blew up.",
                "The rolling stones concert down the road caused a brown out",
                "The salesman drove over the CPU board.",
                "The monitor is plugged into the serial port",
                "Root nameservers are out of sync",
                "electro-magnetic pulses from French above ground nuke testing.",
                "your keyboard's space bar is generating spurious keycodes.",
                "the real ttys became pseudo ttys and vice-versa.",
                "the printer thinks its a router.",
                "the router thinks its a printer.",
                "evil hackers from Serbia.",
                "we just switched to FDDI.",
                "halon system went off and killed the operators.",
                "because Bill Gates is a Jehovah's witness and so nothing can work on St. Swithin's day.",
                "user to computer ratio too high.",
                "user to computer ration too low.",
                "we just switched to Sprint.",
                "it has Intel Inside",
                "Sticky bits on disk.",
                "Power Company having EMP problems with their reactor",
                "The ring needs another token",
                "new management",
                "telnet: Unable to connect to remote host: Connection refused",
                "SCSI Chain overterminated",
                "It's not plugged in.",
                "because of network lag due to too many people playing deathmatch",
                "You put the disk in upside down.",
                "Daemons loose in system.",
                "User was distributing pornography on server; system seized by FBI.",
                "BNC (brain not connected)",
                "UBNC (user brain not connected)",
                "LBNC (luser brain not connected)",
                "disks spinning backwards - toggle the hemisphere jumper.",
                "new guy cross-connected phone lines with ac power bus.",
                "had to use hammer to free stuck disk drive heads.",
                "Too few computrons available.",
                "Flat tire on station wagon with tapes.  ('Never underestimate the bandwidth of a station wagon full of tapes hurling down the highway' Andrew S. Tannenbaum) ",
                "Communications satellite used by the military for star wars.",
                "Party-bug in the Aloha protocol.",
                "Insert coin for new game",
                "Dew on the telephone lines.",
                "Arcserve crashed the server again.",
                "Some one needed the powerstrip, so they pulled the switch plug.",
                "My pony-tail hit the on/off switch on the power strip.",
                "Big to little endian conversion error",
                "You can tune a file system, but you can't tune a fish (from most tunefs man pages)",
                "Dumb terminal",
                "Zombie processes haunting the computer",
                "Incorrect time synchronization",
                "Defunct processes",
                "Stubborn processes",
                "non-redundant fan failure ",
                "monitor VLF leakage",
                "bugs in the RAID",
                "no 'any' key on keyboard",
                "root rot",
                "Backbone Scoliosis",
                "/pub/lunch",
                "excessive collisions & not enough packet ambulances",
                "le0: no carrier: transceiver cable problem?",
                "broadcast packets on wrong frequency",
                "popper unable to process jumbo kernel",
                "NOTICE: alloc: /dev/null: filesystem full",
                "pseudo-user on a pseudo-terminal",
                "Recursive traversal of loopback mount points",
                "Backbone adjustment",
                "OS swapped to disk",
                "vapors from evaporating sticky-note adhesives",
                "sticktion",
                "short leg on process table",
                "multicasts on broken packets",
                "ether leak",
                "Atilla the Hub",
                "endothermal recalibration",
                "filesystem not big enough for Jumbo Kernel Patch",
                "loop found in loop in redundant loopback",
                "system consumed all the paper for paging",
                "permission denied",
                "Reformatting Page. Wait...",
                "..disk or the processor is on fire.",
                "SCSI's too wide.",
                "Proprietary Information.",
                "Just type 'mv * /dev/null'.",
                "runaway cat on system.",
                "Did you pay the new Support Fee?",
                "We only support a 1200 bps connection.",
                "We only support a 28000 bps connection.",
                "Me no internet, only janitor, me just wax floors.",
                "I'm sorry a pentium won't do, you need an SGI to connect with us.",
                "Post-it Note Sludge leaked into the monitor.",
                "the curls in your keyboard cord are losing electricity.",
                "The monitor needs another box of pixels.",
                "RPC_PMAP_FAILURE",
                "kernel panic: write-only-memory (/dev/wom0) capacity exceeded.",
                "Write-only-memory subsystem too slow for this machine. Contact your local dealer.",
                "Just pick up the phone and give modem connect sounds. 'Well you said we should get more lines so we don't have voice lines.'",
                "Quantum dynamics are affecting the transistors",
                "Police are examining all internet packets in the search for a narco-net-trafficker",
                "We are currently trying a new concept of using a live mouse.  Unfortunately, one has yet to survive being hooked up to the computer.....please bear with us.",
                "Your mail is being routed through Germany ... and they're censoring us.",
                "Only people with names beginning with 'A' are getting mail this week (a la Microsoft)",
                "We didn't pay the Internet bill and it's been cut off.",
                "Lightning strikes.",
                "Of course it doesn't work. We've performed a software upgrade.",
                "Change your language to Finnish.",
                "Fluorescent lights are generating negative ions. If turning them off doesn't work, take them out and put tin foil on the ends.",
                "High nuclear activity in your area.",
                "What office are you in? Oh, that one.  Did you know that your building was built over the universities first nuclear research site? And wow, aren't you the lucky one, your office is right over where the core is buried!",
                "The MGs ran out of gas.",
                "The UPS doesn't have a battery backup.",
                "Recursivity.  Call back if it happens again.",
                "Someone thought The Big Red Button was a light switch.",
                "The mainframe needs to rest.  It's getting old, you know.",
                "I'm not sure.  Try calling the Internet's head office -- it's in the book.",
                "The lines are all busy (busied out, that is -- why let them in to begin with?).",
                "Jan  9 16:41:27 huber su: 'su root' succeeded for .... on /dev/pts/1",
                "It's those computer people in X {city of world}.  They keep stuffing things up.",
                "A star wars satellite accidently blew up the WAN.",
                "Fatal error right in front of screen",
                "That function is not currently supported, but Bill Gates assures us it will be featured in the next upgrade.",
                "wrong polarity of neutron flow",
                "Lusers learning curve appears to be fractal",
                "We had to turn off that service to comply with the CDA Bill.",
                "Ionization from the air-conditioning",
                "TCP/IP UDP alarm threshold is set too low.",
                "Someone is broadcasting pygmy packets and the router doesn't know how to deal with them.",
                "The new frame relay network hasn't bedded down the software loop transmitter yet. ",
                "Fanout dropping voltage too much, try cutting some of those little traces",
                "Plate voltage too low on demodulator tube",
                "You did wha... oh _dear_....",
                "CPU needs bearings repacked",
                "Too many little pins on CPU confusing it, bend back and forth until 10-20% are neatly removed. Do _not_ leave metal bits visible!",
                "_Rosin_ core solder? But...",
                "Software uses US measurements, but the OS is in metric...",
                "The computer fleetly, mouse and all.",
                "Your cat tried to eat the mouse.",
                "The Borg tried to assimilate your system. Resistance is futile.",
                "It must have been the lightning storm we had (yesterday) (last week) (last month)",
                "Due to Federal Budget problems we have been forced to cut back on the number of users able to access the system at one time. (namely none allowed....)",
                "Too much radiation coming from the soil.",
                "Unfortunately we have run out of bits/bytes/whatever. Don't worry, the next supply will be coming next week.",
                "Program load too heavy for processor to lift.",
                "Processes running slowly due to weak power supply",
                "Our ISP is having {switching,routing,SMDS,frame relay} problems",
                "We've run out of licenses",
                "Interference from lunar radiation",
                "Standing room only on the bus.",
                "You need to install an RTFM interface.",
                "That would be because the software doesn't work.",
                "That's easy to fix, but I can't be bothered.",
                "Someone's tie is caught in the printer, and if anything else gets printed, he'll be in it too.",
                "We're upgrading /dev/null",
                "The Usenet news is out of date",
                "Our POP server was kidnapped by a weasel.",
                "It's stuck in the Web.",
                "Your modem doesn't speak English.",
                "The mouse escaped.",
                "All of the packets are empty.",
                "The UPS is on strike.",
                "Neutrino overload on the nameserver",
                "Melting hard drives",
                "Someone has messed up the kernel pointers",
                "The kernel license has expired",
                "Netscape has crashed",
                "The cord jumped over and hit the power switch.",
                "It was OK before you touched it.",
                "Bit rot",
                "U.S. Postal Service",
                "Your Flux Capacitor has gone bad.",
                "The Dilithium Crystals need to be rotated.",
                "The static electricity routing is acting up...",
                "Traceroute says that there is a routing problem in the backbone.  It's not our problem.",
                "The co-locator cannot verify the frame-relay gateway to the ISDN server.",
                "High altitude condensation from U.S.A.F prototype aircraft has contaminated the primary subnet mask. Turn off your computer for 9 days to avoid damaging it.",
                "Lawn mower blade in your fan need sharpening",
                "Electrons on a bender",
                "Telecommunications is upgrading. ",
                "Telecommunications is downgrading.",
                "Telecommunications is downshifting.",
                "Hard drive sleeping. Let it wake up on it's own...",
                "Interference between the keyboard and the chair.",
                "The CPU has shifted, and become decentralized.",
                "Due to the CDA, we no longer have a root account.",
                "We ran out of dial tone and we're and waiting for the phone company to deliver another bottle.",
                "You must've hit the wrong any key.",
                "PCMCIA slave driver",
                "The Token fell out of the ring. Call us when you find it.",
                "The hardware bus needs a new token.",
                "Too many interrupts",
                "Not enough interrupts",
                "The data on your hard drive is out of balance.",
                "Digital Manipulator exceeding velocity parameters",
                "appears to be a Slow/Narrow SCSI-0 Interface problem",
                "microelectronic Riemannian curved-space fault in write-only file system",
                "fractal radiation jamming the backbone",
                "routing problems on the neural net",
                "IRQ-problems with the Un-Interruptible-Power-Supply",
                "CPU-angle has to be adjusted because of vibrations coming from the nearby road",
                "emissions from GSM-phones",
                "CD-ROM server needs recalibration",
                "firewall needs cooling",
                "asynchronous inode failure",
                "transient bus protocol violation",
                "incompatible bit-registration operators",
                "your process is not ISO 9000 compliant",
                "You need to upgrade your VESA local bus to a MasterCard local bus.",
                "The recent proliferation of Nuclear Testing",
                "Elves on strike. (Why do they call EMAG Elf Magic)",
                "Internet exceeded Luser level, please wait until a luser logs off before attempting to log back on.",
                "Your EMAIL is now being delivered by the USPS.",
                "Your computer hasn't been returning all the bits it gets from the Internet.",
                "You've been infected by the Telescoping Hubble virus.",
                "Scheduled global CPU outage",
                "Your Pentium has a heating problem - try cooling it with ice cold water.(Do not turn off your computer, you do not want to cool down the Pentium Chip while he isn't working, do you?)",
                "Your processor has processed too many instructions.  Turn it off immediately, do not type any commands!!",
                "Your packets were eaten by the terminator",
                "Your processor does not develop enough heat.",
                "We need a licensed electrician to replace the light bulbs in the computer room.",
                "The POP server is out of Coke",
                "Fiber optics caused gas main leak",
                "Server depressed, needs Prozac",
                "quantum decoherence",
                "those damn raccoons!",
                "suboptimal routing experience",
                "A plumber is needed, the network drain is clogged",
                "50% of the manual is in .pdf readme files",
                "the AA battery in the wallclock sends magnetic interference",
                "the xy axis in the trackball is coordinated with the summer solstice",
                "the butane lighter causes the pincushioning",
                "old inkjet cartridges emanate barium-based fumes",
                "manager in the cable duct",
                "We'll fix that in the next (upgrade, update, patch release, service pack).",
                "HTTPD Error 666 : BOFH was here",
                "HTTPD Error 4004 : very old Intel cpu - insufficient processing power",
                "The ATM board has run out of 10 pound notes.  We are having a whip round to refill it, care to contribute ?",
                "Network failure -  call NBC",
                "Having to manually track the satellite.",
                "Your/our computer(s) had suffered a memory leak, and we are waiting for them to be topped up.",
                "The rubber band broke",
                "We're on Token Ring, and it looks like the token got loose.",
                "Stray Alpha Particles from memory packaging caused Hard Memory Error on Server.",
                "paradigm shift...without a clutch",
                "PEBKAC (Problem Exists Between Keyboard And Chair)",
                "The cables are not the same length.",
                "Second-system effect.",
                "Chewing gum on /dev/sd3c",
                "Boredom in the Kernel.",
                "the daemons! the daemons! the terrible daemons!",
                "I'd love to help you -- it's just that the Boss won't let me near the computer. ",
                "struck by the Good Times virus",
                "YOU HAVE AN I/O ERROR -> Incompetent Operator error",
                "Your parity check is overdrawn and you're out of cache.",
                "Communist revolutionaries taking over the server room and demanding all the computers in the building or they shoot the sysadmin. Poor misguided fools.",
                "Plasma conduit breach",
                "Out of cards on drive D:",
                "Sand fleas eating the Internet cables",
                "parallel processors running perpendicular today",
                "ATM cell has no roaming feature turned on, notebooks can't connect",
                "Webmasters kidnapped by evil cult.",
                "Failure to adjust for daylight savings time.",
                "Virus transmitted from computer to sysadmins.",
                "Virus due to computers having unsafe sex.",
                "Incorrectly configured static routes on the corerouters.",
                "Forced to support NT servers; sysadmins quit.",
                "Suspicious pointer corrupted virtual machine",
                "It's the InterNIC's fault.",
                "Root name servers corrupted.",
                "Budget cuts forced us to sell all the power cords for the servers.",
                "Someone hooked the twisted pair wires into the answering machine.",
                "Operators killed by year 2000 bug bite.",
                "We've picked COBOL as the language of choice.",
                "Operators killed when huge stack of backup tapes fell over.",
                "Robotic tape changer mistook operator's tie for a backup tape.",
                "Someone was smoking in the computer room and set off the halon systems.",
                "Your processor has taken a ride to Heaven's Gate on the UFO behind Hale-Bopp's comet.",
                "it's an ID-10-T error",
                "Dyslexics retyping hosts file on servers",
                "The Internet is being scanned for viruses.",
                "Your computer's union contract is set to expire at midnight.",
                "Bad user karma.",
                "/dev/clue was linked to /dev/null",
                "Increased sunspot activity.",
                "We already sent around a notice about that.",
                "It's union rules. There's nothing we can do about it. Sorry.",
                "Interference from the Van Allen Belt.",
                "Jupiter is aligned with Mars.",
                "Redundant ACLs. ",
                "Mail server hit by UniSpammer.",
                "T-1's congested due to porn traffic to the news server.",
                "Data for intranet got routed through the extranet and landed on the internet.",
                "We are a 100% Microsoft Shop.",
                "We are Microsoft.  What you are experiencing is not a problem; it is an undocumented feature.",
                "Sales staff sold a product we don't offer.",
                "Secretary sent chain letter to all 5000 employees.",
                "Sysadmin didn't hear pager go off due to loud music from bar-room speakers.",
                "Sysadmin accidentally destroyed pager with a large hammer.",
                "Sysadmins unavailable because they are in a meeting talking about why they are unavailable so much.",
                "Bad cafeteria food landed all the sysadmins in the hospital.",
                "Route flapping at the NAP.",
                "Computers under water due to SYN flooding.",
                "The vulcan-death-grip ping has been applied.",
                "Electrical conduits in machine room are melting.",
                "Traffic jam on the Information Superhighway.",
                "Radial Telemetry Infiltration",
                "Cow-tippers tipped a cow onto the server.",
                "tachyon emissions overloading the system",
                "Maintenance window broken",
                "We're out of slots on the server",
                "Computer room being moved.  Our systems are down for the weekend.",
                "Sysadmins busy fighting SPAM.",
                "Repeated reboots of the system failed to solve problem",
                "Feature was not beta tested",
                "Domain controller not responding",
                "Someone else stole your IP address, call the Internet detectives!",
                "It's not RFC-822 compliant.",
                "operation failed because: there is no message for this error (#1014)",
                "stop bit received",
                "internet is needed to catch the etherbunny",
                "network down, IP packets delivered via UPS",
                "Firmware update in the coffee machine",
                "Temporal anomaly",
                "Mouse has out-of-cheese-error",
                "Borg implants are failing",
                "Borg nanites have infested the server",
                "error: one bad user found in front of screen",
                "Please state the nature of the technical emergency",
                "Internet shut down due to maintenance",
                "Daemon escaped from pentagram",
                "crop circles in the corn shell",
                "sticky bit has come loose",
                "Hot Java has gone cold",
                "Cache miss - please take better aim next time",
                "Hash table has woodworm",
                "Trojan horse ran out of hay",
                "Zombie processes detected, machine is haunted.",
                "overflow error in /dev/null",
                "Browser's cookie is corrupted -- someone's been nibbling on it.",
                "Mailer-daemon is busy burning your message in hell.",
                "According to Microsoft, it's by design",
                "vi needs to be upgraded to vii",
                "greenpeace free'd the mallocs",
                "astropneumatic oscillations in the water-cooling",
                "Somebody ran the operating system through a spelling checker.",
                "Rhythmic variations in the voltage reaching the power supply.",
                "Keyboard Actuator Failure.  Order and Replace.",
                "Packet held up at customs.",
                "Propagation delay.",
                "High line impedance.",
                "Someone set us up the bomb.",
                "Power surges on the Underground.",
                "Don't worry; it's been deprecated. The new one is worse.",
                "Excess condensation in cloud network",
                "It is a layer 8 problem",
                "The math co-processor had an overflow error that leaked out and shorted the RAM",
                "Leap second overloaded RHEL6 servers",
                "DNS server drank too much and had a hiccup",
                "Your machine had the fuses in backwards.",
                "TK did it."
            };
            // Return a random gif
            return Messages.PickRandom();

        }
        /// <summary>
        /// Roll a random number generated
        /// </summary>
        /// <returns></returns>
        public static int Roll(int number)
        {
            Random rnd = new Random();
            return rnd.Next(1, number);
        }
        /// <summary>
        /// Convert a number to chicken nuggets
        /// </summary>
        public static int Nuggets(int number)
        {
            var cost = number / 9;
            return cost * 40;
        }

    }
    /// <summary>
    /// Adding on to the list class using linq
    /// </summary>
    public static class EnumerableExtension
    {
        /// <summary>
        /// Tack on pick random to a list
        /// </summary>
        public static T PickRandom<T>(this IEnumerable<T> source)
        {
            // Pick a single random
            return source.PickRandom(1).Single();
        }

        /// <summary>
        /// Take a choice using shuffle
        /// </summary>
        public static IEnumerable<T> PickRandom<T>(this IEnumerable<T> source, int count)
        {
            return source.Shuffle().Take(count);
        }

        /// <summary>
        /// Shuffle the list
        /// </summary>
        public static IEnumerable<T> Shuffle<T>(this IEnumerable<T> source)
        {
            return source.OrderBy(x => Guid.NewGuid());
        }
    }
}
